import Head from 'next/head'
import Header from '../components/Header'
import Feed from '../components/Feed'
import UploadModel from '../components/UploadModel'

export default function Home() {
  return (
    <div className='bg-gray-50 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header Section */}
      <Header></Header>

      {/* Feed Section */}

      <Feed></Feed>

      {/* Modal Section */}

      <UploadModel></UploadModel>


    </div>
  )
}
